version: "3.8"

services:
  web:
    build: .
    container_name: lab05_php
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html/api
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: lab05_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab5
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lab05_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

volumes:
  db_data:
